#!/bin/bash

#==============================================================================
# Title:                Spark Message (service)
# Description:          This is an external service for Cloud Center to post a
#                       message to a Spark room.
#
# Author:          		Rob Edwards (robedwa/@clijockey)
# Date:                 01/11/16
# Version:              0.1
# Dependencies:
# Limitations/issues:   Early days of the service
#                       Make proxy settings optional
#==============================================================================


. /utils.sh


SVCNAME="spark"

postMessage(){
    print_log "Posting spark message!"
    print_log "Proxy set: $proxy"

    ## Message - Create (Lab)
    #
    curl --proxy $proxy \
        -X "POST" "https://api.ciscospark.com/v1/messages" \
        -H "Authorization: $Authorization" \
        -H "Content-Type: application/json" \
        -d $"{ \"roomId\": \"$roomId\",
            \"markdown\": \"$1\" }"

    print_log "Posted spark message!"
}

case $1 in
    update)
        postMessage "Application [$parentJobName](https://cloud-center.ukidcv.cisco.com/#job/runs/$parentJobId) has been **updated**"
        ;;
	start)
		postMessage "Application [$parentJobName](https://cloud-center.ukidcv.cisco.com/#job/runs/$parentJobId) has been **started**"
		;;
	stop)
        postMessage "Application [$parentJobName](https://cloud-center.ukidcv.cisco.com/#job/runs/$parentJobId) has been **stopped**"
		;;
	suspend)
        postMessage "Application [$parentJobName](https://cloud-center.ukidcv.cisco.com/#job/runs/$parentJobId) has been **suspend**"
		;;
	resume)
        postMessage "Application [$parentJobName](https://cloud-center.ukidcv.cisco.com/#job/runs/$parentJobId) has been **resumed**"
		;;
	*)
		echo "unknown command"
		exit 127
		;;
esac
